version: '3'
services:
  nginx:
    image: "nginx"
    ports:
      - "8080:8080"
    links:
      - "loki"
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
  grafana:
    image: "grafana/grafana"
    ports: 
      - "3000:3000"
    links:
      - "loki"
    volumes:
      - grafana-data:/var/lib/grafana
  loki:
    image: "grafana/loki"
    ports: 
      - "3100:3100"
    volumes: 
      - loki-data:/loki
volumes:
  loki-data:
  grafana-data: