version: '3'
services:
  proxy:
    build: .
    ports:
      - "8080:8080"
    links:
      - "loki"
  grafana:
    image: "grafana/grafana"
    ports: 
      - "3000:3000"
    links:
      - "loki"
  loki:
    image: "grafana/loki"
    ports: 
      - "3100:3100"
    volumes: 
      - loki-data:/loki
volumes:
  loki-data:
